### ISSUE TITLE
ipctool collects complete firmware dumps without the user's knowledge or approval

### ISSUE THREAD

**Issue by gckzl** [OpenIPC/ipctool#78]
When run without arguments, ipctool prints a summary about the device information, as is documented in the README.

However, it also starts a background process that uploads the entire device storage to an S3 bucket, without asking for confirmation from the user, nor even letting them know that this is happening.  This behaviour is not documented anywhere, and it is completely unexpected given the description of the tool.

This "feature" may have been implemented with the best intentions, but the collected data contains personal information, such as /etc/passwd files, wifi passwords, SSL/SSH/VPN keys, etc.  As such, it is in violation of the GDPR.  As a general principle, if you want the user's help in collecting device information, you should __ask__ for that help, not do it behind the user's back.  Users of unsuported devices will be more than happy to assist you, and you'll also avoid getting firmware dumps for devices you already support.

I'm happy to provide a patch removing this unwanted behavior, but first I'm curious to hear your thoughts on this.

**Comment by easy-and-simple** [comment]
GDPR just lies people that their personal data is protected, while it isn't and is violated in everything. Data collected in compliance with GDPR is much harmful than if someone stolen it against GDPR rules. You are forced to supply your personal data voluntary for everything. If you connect your camera to Internet all of your data is transmitted in any case. All data on your computer that is much more sensitive is transmitted to internet on any reason and without reason encrypted or raw this doesn't matter

**Comment by widgetii** [comment]
> I'm happy to provide a patch removing this unwanted behavior, but first I'm curious to hear your thoughts on this.

I have no objections to remove making autodumps in default build, but rather of removing such function completely, I'd add compilation flags to keep it when it's necessary because we use it internally in our research process. Feel free to make a PR

**Comment by widgetii** [comment]
> My suggestions would be the following:
> 
> * stop making autodumps when run without arguments.
> * add a separate `upload` command, to make it clear the data is leaving the local network
> * move the backup / upload work to the main process: no more background processes, it makes it look like you're trying to hide something
> 
> So, I wouldn't remove the upload functionality, I would just make it explicit.
> 
> I'll get started on a pull request.

Looks like a good plan

Actually, we have `-w` option that does the same as described above (waits until upload finished and then exits). I think it would be okay to change it to separate `upload` command https://github.com/OpenIPC/ipctool/blob/master/src/main.c#L269

**Comment by easy-and-simple** [comment]
@gckzl you are far away from the truth, and you have no any idea where you live and what happens around you. 
1. Your super-duper law GDPR is law only in EU and EU doesn't include all counties on earth. EU is just some little part of the earth controlled by stupid pensioners
2. GDPR is harmful because it leads to excessive data collection on top of all legally. Before GDPR  if someone has collected redundant data it was not normal. Now after GDPR every one who can, collects as many data as possible, because it is personal data operator. 
3. Every time people try to protect their personal data with help of GDPR, there some conditions that they don't meet
4. GDPR doesn't protect people it protect governments and their clerks. 
5. GDPR is law for slaves like you, that on top of all are fighting for their legal right to be slaves
6. Your can't use any product or service including social services, if you don't agree to supply all of your personal data. You will die on street if you reject to supply all of your personal data to the hospital.
But there is hope for you. It is called "don't track me" browser option. Activate it and have happy sleeps  haha
